server:
  port: 8445
  
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/toggledb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: ghim
      password: rlwjd2131@
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   

