server:
  port: 8445
  
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://118.219.232.12:3306/smbang7103?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: smbang7103
      password: cjfxhdqhdks12!@
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   

