server:
  port: 8445
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://118.219.232.12:3306/smbang7103?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: smbang7103
    password: cjfxhdqhdks12!@
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    
logging:
  config: classpath:logback-${spring.profiles.active}.xml
  level: 
    org.springframework.web.filter: debug